# Generated by Django 4.2 on 2026-04-20 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('training_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_10_scores', models.JSONField(default=list, help_text='Last 10 form scores')),
                ('average_score', models.FloatField(default=0.0, help_text='Average of last 10')),
                ('min_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('plateaued', 'Plateaued')], default='stable', max_length=20)),
                ('trend_slope', models.FloatField(default=0.0, help_text='Positive = improving')),
                ('consistency_score', models.FloatField(default=0.0, help_text='How consistent performance 0-100')),
                ('recommendation', models.CharField(choices=[('increase', 'Increase Difficulty'), ('maintain', 'Maintain Current'), ('decrease', 'Decrease Difficulty'), ('modify', 'Modify Exercise'), ('progress', 'Progress to Variant')], default='maintain', max_length=20)),
                ('recommended_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, null=True)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('total_sessions', models.IntegerField(default=0, help_text='Total sessions with this exercise')),
                ('days_since_last', models.IntegerField(default=0, help_text='Days since last attempt')),
                ('adaptation_count', models.IntegerField(default=0, help_text='Number of times adapted')),
                ('last_adapted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Difficulty Adaptation',
                'verbose_name_plural': 'Difficulty Adaptations',
            },
        ),
        migrations.CreateModel(
            name='ExerciseClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(choices=[('movement_pattern', 'Movement Pattern'), ('equipment', 'Equipment'), ('intensity', 'Intensity'), ('plane_of_motion', 'Plane of Motion'), ('primary_joint', 'Primary Joint'), ('secondary_joint', 'Secondary Joint'), ('stabilization', 'Stabilization'), ('complexity_level', 'Complexity Level'), ('recovery_focus', 'Recovery Focus')], max_length=50)),
                ('classification_value', models.CharField(help_text='Classification label', max_length=100)),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight for matching')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise Classification',
                'verbose_name_plural': 'Exercise Classifications',
            },
        ),
        migrations.CreateModel(
            name='InjuryRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('joint_angle', 'Joint Angle Exceeded'), ('range_of_motion', 'Excessive ROM'), ('joint_compression', 'Joint Compression'), ('shear_force', 'Shear Force Detected'), ('instability', 'Joint Instability'), ('asymmetry', 'Movement Asymmetry'), ('muscle_imbalance', 'Muscle Imbalance'), ('fatigue_risk', 'Fatigue-Related Risk')], max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('joint_name', models.CharField(help_text='e.g., left_knee, right_shoulder', max_length=100)),
                ('current_angle', models.FloatField(blank=True, help_text='Current joint angle in degrees', null=True)),
                ('safe_range_min', models.FloatField(blank=True, help_text='Min safe angle', null=True)),
                ('safe_range_max', models.FloatField(blank=True, help_text='Max safe angle', null=True)),
                ('angle_exceeded_by', models.FloatField(blank=True, help_text='Degrees exceeded', null=True)),
                ('severity_score', models.FloatField(help_text='Risk severity 0-100')),
                ('repetition_count', models.IntegerField(default=1, help_text='How many times this occurred')),
                ('description', models.TextField(help_text='Detailed explanation of the risk')),
                ('recommendation', models.TextField(help_text='What user should do to reduce risk')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Injury Risk Alert',
                'verbose_name_plural': 'Injury Risk Alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='JointSafetyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_name', models.CharField(help_text='e.g., knee, shoulder_external', max_length=100)),
                ('movement_axis', models.CharField(choices=[('flexion_extension', 'Flexion/Extension'), ('abduction_adduction', 'Abduction/Adduction'), ('rotation', 'Rotation'), ('circumduction', 'Circumduction')], max_length=50)),
                ('exercise_type', models.CharField(help_text='Type of exercise (e.g., squatting, pressing, rotating)', max_length=100)),
                ('normal_min_angle', models.FloatField(help_text='Normal minimum safe angle in degrees')),
                ('normal_max_angle', models.FloatField(help_text='Normal maximum safe angle in degrees')),
                ('conservative_min_angle', models.FloatField(help_text='Conservative minimum (for recovery)')),
                ('conservative_max_angle', models.FloatField(help_text='Conservative maximum (for recovery)')),
                ('warning_threshold', models.FloatField(default=5.0, help_text='Degrees beyond safe range before warning')),
                ('critical_threshold', models.FloatField(default=15.0, help_text='Degrees beyond safe range before critical alert')),
                ('source', models.CharField(help_text='Source of safe range data (e.g., ISO standard, clinical study)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Joint Safety Profile',
                'verbose_name_plural': 'Joint Safety Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDifficultyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression_strategy', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive'), ('adaptive', 'Adaptive')], default='adaptive', max_length=20)),
                ('min_score_threshold', models.FloatField(default=70.0, help_text='Minimum score before suggesting progression (0-100)')),
                ('consistency_threshold', models.FloatField(default=80.0, help_text='Consistency score required for progression (0-100)')),
                ('injury_risk_sensitivity', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', help_text='How sensitive to injury warnings', max_length=20)),
                ('max_allowed_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('sessions_before_review', models.IntegerField(default=5, help_text='Review difficulty after N sessions')),
                ('auto_adapt_enabled', models.BooleanField(default=True)),
                ('notify_on_risk', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Difficulty Preference',
                'verbose_name_plural': 'User Difficulty Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='jointsafetyprofile',
            index=models.Index(fields=['joint_name', 'is_active'], name='advanced_fe_joint_n_2c19d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jointsafetyprofile',
            unique_together={('joint_name', 'movement_axis', 'exercise_type')},
        ),
        migrations.AddField(
            model_name='injuryriskalert',
            name='pose_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_alerts', to='ai_engine.poseanalysis'),
        ),
        migrations.AddField(
            model_name='injuryriskalert',
            name='session_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_alerts', to='training_sessions.sessionexercise'),
        ),
        migrations.AddField(
            model_name='injuryriskalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_risk_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseclassification',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='difficultyadaptation',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='difficultyadaptation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_adaptations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='injuryriskalert',
            index=models.Index(fields=['user', '-detected_at'], name='advanced_fe_user_id_552249_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryriskalert',
            index=models.Index(fields=['risk_level'], name='advanced_fe_risk_le_2ee5df_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryriskalert',
            index=models.Index(fields=['is_resolved'], name='advanced_fe_is_reso_e26079_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseclassification',
            index=models.Index(fields=['exercise', 'classification_type'], name='advanced_fe_exercis_d1cd25_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseclassification',
            index=models.Index(fields=['classification_type', 'classification_value'], name='advanced_fe_classif_d3535a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseclassification',
            unique_together={('exercise', 'classification_type', 'classification_value')},
        ),
        migrations.AddIndex(
            model_name='difficultyadaptation',
            index=models.Index(fields=['user', 'trend'], name='advanced_fe_user_id_ba0f94_idx'),
        ),
        migrations.AddIndex(
            model_name='difficultyadaptation',
            index=models.Index(fields=['exercise', 'recommendation'], name='advanced_fe_exercis_3575b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='difficultyadaptation',
            unique_together={('user', 'exercise')},
        ),
    ]
