# Generated by Django 4.2 on 2026-04-20 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('pose_detection', 'Pose Detection'), ('form_analysis', 'Form Analysis'), ('movement_tracking', 'Movement Tracking')], max_length=50)),
                ('accuracy_score', models.FloatField(help_text='Accuracy percentage 0-100')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('improvement_areas', models.JSONField(default=list, help_text='List of areas to improve')),
                ('positive_feedback', models.JSONField(default=list, help_text='What went well')),
                ('overall_score', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session_exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='training_sessions.sessionexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedbacks',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PoseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('form_score', models.FloatField(help_text='Form quality 0-100')),
                ('confidence_level', models.FloatField(help_text='Model confidence 0-100')),
                ('detected_joints', models.JSONField(default=dict, help_text='JSON with joint positions')),
                ('issues_detected', models.JSONField(default=list, help_text='List of form issues detected')),
                ('recommendations', models.TextField(blank=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_analyses', to='training_sessions.sessionexercise')),
            ],
            options={
                'verbose_name': 'Pose Analysis',
                'verbose_name_plural': 'Pose Analyses',
                'ordering': ['session_exercise', 'frame_number'],
                'unique_together': {('session_exercise', 'frame_number')},
            },
        ),
    ]
