# Generated by Django 4.2 on 2026-04-20 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(help_text='ID of the exercise')),
                ('exercise_name', models.CharField(max_length=200)),
                ('total_times_completed', models.IntegerField(default=0)),
                ('average_form_score', models.FloatField(default=0.0)),
                ('average_duration_seconds', models.IntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0, help_text='How often exercise is used')),
                ('difficulty_distribution', models.JSONField(default=dict, help_text='Distribution of difficulty levels in sessions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise Statistics',
                'verbose_name_plural': 'Exercise Statistics',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions_completed', models.IntegerField(default=0)),
                ('total_exercises_completed', models.IntegerField(default=0)),
                ('average_form_score', models.FloatField(default=0.0, help_text='Average form score 0-100')),
                ('total_minutes_exercised', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0, help_text='Current consecutive days exercising')),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(help_text='Report metrics and data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions_completed', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('average_form_score', models.FloatField(default=0.0)),
                ('total_minutes_exercised', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Metrics',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
