# Generated by Django 4.2 on 2026-04-20 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(help_text="Type of injury (e.g., 'knee pain', 'rotator cuff')", max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.IntegerField(default=4, help_text='Duration in weeks')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('weekly_plan', models.JSONField(help_text='Structured weekly plan with exercises and rest days. Format: {day: [exercises], notes}')),
                ('goals', models.JSONField(default=list, help_text='List of therapeutic goals')),
                ('precautions', models.JSONField(default=list, help_text='Important precautions and contraindications')),
                ('progression_strategy', models.TextField(blank=True, help_text='How to progress through the plan')),
                ('created_from_performance', models.JSONField(default=dict, help_text='Performance metrics used to generate the plan')),
                ('gpt_response', models.JSONField(blank=True, help_text='Full GPT response for reference and debugging', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_score', models.FloatField(default=0.0, help_text="User's progress on this plan (0-100)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the plan was generated by GPT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapy Plan',
                'verbose_name_plural': 'Therapy Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Which week in the plan (1-based)')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('exercise_name', models.CharField(help_text='Name of the exercise', max_length=255)),
                ('description', models.TextField(help_text='How to perform this exercise')),
                ('sets', models.IntegerField(default=3, help_text='Number of sets')),
                ('reps', models.IntegerField(default=10, help_text='Number of reps per set')),
                ('duration_minutes', models.IntegerField(default=1, help_text='Duration per set in minutes')),
                ('rest_seconds', models.IntegerField(default=60, help_text='Rest between sets')),
                ('modifications', models.TextField(blank=True, help_text='Variations or modifications for different ability levels')),
                ('precautions', models.TextField(blank=True, help_text='Safety precautions specific to this exercise')),
                ('benefits', models.TextField(blank=True, help_text='Why this exercise is beneficial')),
                ('progression_week', models.IntegerField(default=1, help_text='Which week to increase intensity/difficulty')),
                ('progression_notes', models.TextField(blank=True, help_text='How to progress this exercise')),
                ('is_rest_day', models.BooleanField(default=False, help_text='Mark as rest day')),
                ('order', models.IntegerField(default=0, help_text="Order in the day's routine")),
                ('exercise', models.ForeignKey(blank=True, help_text='Reference to the Exercise model if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
                ('therapy_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assignments', to='therapy_plans.therapyplan')),
            ],
            options={
                'verbose_name': 'Weekly Exercise',
                'verbose_name_plural': 'Weekly Exercises',
                'ordering': ['therapy_plan', 'week_number', 'day_of_week', 'order'],
                'unique_together': {('therapy_plan', 'week_number', 'day_of_week', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='therapyplan',
            index=models.Index(fields=['user', '-created_at'], name='therapy_pla_user_id_cefc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='therapyplan',
            index=models.Index(fields=['status'], name='therapy_pla_status_c0aa5b_idx'),
        ),
    ]
