from django.db import models
from django.contrib.auth.models import User
from exercises.models import Exercise


class TherapyPlan(models.Model):
    """
    Stores personalized therapy plans generated by AI.
    Each plan is customized based on injury type and user performance history.
    """
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('archived', 'Archived'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='therapy_plans')
    injury_type = models.CharField(max_length=255, help_text="Type of injury (e.g., 'knee pain', 'rotator cuff')")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    
    # Plan details
    title = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    duration_weeks = models.IntegerField(default=4, help_text="Duration in weeks")
    difficulty_level = models.CharField(
        max_length=20,
        choices=[
            ('beginner', 'Beginner'),
            ('intermediate', 'Intermediate'),
            ('advanced', 'Advanced'),
        ],
        default='beginner'
    )
    
    # Plan structure
    weekly_plan = models.JSONField(
        help_text="Structured weekly plan with exercises and rest days. Format: {day: [exercises], notes}"
    )
    goals = models.JSONField(default=list, help_text="List of therapeutic goals")
    precautions = models.JSONField(default=list, help_text="Important precautions and contraindications")
    progression_strategy = models.TextField(blank=True, help_text="How to progress through the plan")
    
    # Metadata
    created_from_performance = models.JSONField(
        default=dict, 
        help_text="Performance metrics used to generate the plan"
    )
    gpt_response = models.JSONField(
        null=True, 
        blank=True, 
        help_text="Full GPT response for reference and debugging"
    )
    
    # Tracking
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    progress_score = models.FloatField(
        default=0.0, 
        help_text="User's progress on this plan (0-100)"
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    generated_at = models.DateTimeField(auto_now_add=True, help_text="When the plan was generated by GPT")

    def __str__(self):
        return f"{self.user.username} - {self.injury_type} Plan"

    class Meta:
        verbose_name = 'Therapy Plan'
        verbose_name_plural = 'Therapy Plans'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['status']),
        ]


class WeeklyExercise(models.Model):
    """
    Individual exercise assignment in a weekly therapy plan.
    Links a therapy plan to specific exercises for each day of the week.
    """
    DAY_CHOICES = [
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday'),
    ]

    therapy_plan = models.ForeignKey(
        TherapyPlan, 
        on_delete=models.CASCADE, 
        related_name='exercise_assignments'
    )
    week_number = models.IntegerField(help_text="Which week in the plan (1-based)")
    day_of_week = models.CharField(max_length=20, choices=DAY_CHOICES)
    exercise = models.ForeignKey(
        Exercise, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        help_text="Reference to the Exercise model if available"
    )
    
    # Exercise details
    exercise_name = models.CharField(max_length=255, help_text="Name of the exercise")
    description = models.TextField(help_text="How to perform this exercise")
    sets = models.IntegerField(default=3, help_text="Number of sets")
    reps = models.IntegerField(default=10, help_text="Number of reps per set")
    duration_minutes = models.IntegerField(default=1, help_text="Duration per set in minutes")
    rest_seconds = models.IntegerField(default=60, help_text="Rest between sets")
    
    # Modifications and notes
    modifications = models.TextField(
        blank=True, 
        help_text="Variations or modifications for different ability levels"
    )
    precautions = models.TextField(
        blank=True, 
        help_text="Safety precautions specific to this exercise"
    )
    benefits = models.TextField(blank=True, help_text="Why this exercise is beneficial")
    
    # Progression
    progression_week = models.IntegerField(
        default=1, 
        help_text="Which week to increase intensity/difficulty"
    )
    progression_notes = models.TextField(blank=True, help_text="How to progress this exercise")
    
    # Tracking
    is_rest_day = models.BooleanField(default=False, help_text="Mark as rest day")
    order = models.IntegerField(default=0, help_text="Order in the day's routine")

    def __str__(self):
        return f"Week {self.week_number} {self.day_of_week}: {self.exercise_name}"

    class Meta:
        verbose_name = 'Weekly Exercise'
        verbose_name_plural = 'Weekly Exercises'
        unique_together = ['therapy_plan', 'week_number', 'day_of_week', 'order']
        ordering = ['therapy_plan', 'week_number', 'day_of_week', 'order']
